[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "en"
multilingual = false
src = "src"
title = "Frequently Asked Questions"

[build]
create-missing = true

[output.html]
no-section-label = true
git-repository-url = "https://github.com/ankitects/faqs/"

#[output.linkcheck]
#optional = true
#warning-policy = "warn"
#follow-web-links = true
## quora dislikes bots, and tenderapp doesn't have statically checkable anchors
#exclude = [ 'quora\.com', 'anki\.tenderapp\.com/.*#.*' ]
